/****************************************************************************
*   Generated by ACUITY 6.30.22
*   Match ovxlib 1.1.70
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_H_
#define _VNN_POST_PROCESS_H_

vsi_status vnn_PostProcessYolov8nPosePcq(vsi_nn_graph_t *graph);

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

uint32_t vnn_GetPostProcessMapCount();

#endif
